# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sort.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 540)
        MainWindow.setStyleSheet("background-color: rgb(210, 223, 235);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BubbleSort = QtWidgets.QPushButton(self.centralwidget)
        self.BubbleSort.setGeometry(QtCore.QRect(10, 10, 161, 61))
        self.BubbleSort.setStyleSheet("background-color: rgb(99, 82, 210);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "font: 75 14pt \"Times New Roman\";"
                                      "border:none;\n"
                                      "border-radius:20px;")
        self.BubbleSort.setObjectName("BubbleSort")
        self.InsertionSort = QtWidgets.QPushButton(self.centralwidget)
        self.InsertionSort.setGeometry(QtCore.QRect(10, 80, 161, 61))
        self.InsertionSort.setStyleSheet("background-color: rgb(99, 82, 210);\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "font: 75 14pt \"Times New Roman\";"
                                         "border:none;\n"
                                         "border-radius:20px;")
        self.InsertionSort.setObjectName("InsertionSort")
        self.SelectionSort = QtWidgets.QPushButton(self.centralwidget)
        self.SelectionSort.setGeometry(QtCore.QRect(10, 150, 161, 61))
        self.SelectionSort.setStyleSheet("background-color: rgb(99, 82, 210);\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "font: 75 14pt \"Times New Roman\";"
                                         "border:none;\n"
                                         "border-radius:20px;")
        self.SelectionSort.setObjectName("SelectionSort")
        self.MergeSort = QtWidgets.QPushButton(self.centralwidget)
        self.MergeSort.setGeometry(QtCore.QRect(10, 220, 161, 61))
        self.MergeSort.setStyleSheet("background-color: rgb(99, 82, 210);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "font: 75 14pt \"Times New Roman\";"
                                     "border:none;\n"
                                     "border-radius:20px;")
        self.MergeSort.setObjectName("MergeSort")
        self.QuickSort = QtWidgets.QPushButton(self.centralwidget)
        self.QuickSort.setGeometry(QtCore.QRect(10, 290, 161, 61))
        self.QuickSort.setStyleSheet("background-color: rgb(99, 82, 210);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "font: 75 14pt \"Times New Roman\";"
                                     "border:none;\n"
                                     "border-radius:20px;")
        self.QuickSort.setObjectName("QuickSort")
        self.CountingSort = QtWidgets.QPushButton(self.centralwidget)
        self.CountingSort.setGeometry(QtCore.QRect(10, 360, 161, 61))
        self.CountingSort.setStyleSheet("background-color: rgb(99, 82, 210);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "font: 75 14pt \"Times New Roman\";"
                                        "border:none;\n"
                                        "border-radius:20px;")
        self.CountingSort.setObjectName("CountingSort")
        self.RadixSort = QtWidgets.QPushButton(self.centralwidget)
        self.RadixSort.setGeometry(QtCore.QRect(10, 430, 161, 61))
        self.RadixSort.setStyleSheet("background-color: rgb(99, 82, 210);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "font: 75 14pt \"Times New Roman\";"
                                     "border:none;\n"
                                     "border-radius:20px;")
        self.RadixSort.setObjectName("RadixSort")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 51, 21))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
                                 "font: 75 12pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.Input = QtWidgets.QLineEdit(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(220, 30, 241, 81))
        self.Input.setObjectName("Input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 120, 41, 20))
        self.label_2.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(220, 150, 241, 341))
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BubbleSort.setText(_translate("MainWindow", "Bubble Sort"))
        self.InsertionSort.setText(_translate("MainWindow", "Insertion Sort"))
        self.SelectionSort.setText(_translate("MainWindow", "Selection Sort"))
        self.MergeSort.setText(_translate("MainWindow", "Merge Sort"))
        self.QuickSort.setText(_translate("MainWindow", "Quick Sort"))
        self.CountingSort.setText(_translate("MainWindow", "Couting Sort"))
        self.RadixSort.setText(_translate("MainWindow", "Radix Sort"))
        self.label.setText(_translate("MainWindow", "input"))
        self.label_2.setText(_translate("MainWindow", "output"))

        # -------------------------- connect buttons to functions -------------------
        self.BubbleSort.clicked.connect(self.getData)
        self.InsertionSort.clicked.connect(self.getData2)

    def getData(self):
        def bubbleSort(arr):
            n = len(arr)
            for i in range(n - 1):
                for j in range(0, n - i - 1):
                    if arr[j] > arr[j + 1]:
                        arr[j], arr[j + 1] = arr[j + 1], arr[j]
                    print(" ".join(str(x) for x in arr))
                    self.output.setText(" ".join(str(x) for x in arr))

        # arr = [64, 34, 25, 12, 22, 11, 90]
        arr = self.Input.text()
        arr = arr.split()
        bubbleSort(arr)

    def getData2(self):
        def insertionSort(arr):
            for i in range(1, len(arr)):
                key = arr[i]
                j = i - 1
                while j >= 0 and key < arr[j]:
                    arr[j + 1] = arr[j]
                    j -= 1
                arr[j + 1] = key
                print(" ".join(str(x) for x in arr))
                self.output.setText(" ".join(str(x) for x in arr))

        # arr = [12, 11, 13, 5, 6]
        arr = self.Input.text()
        arr = arr.split()
        insertionSort(arr)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
